# Libs

In [1]:
import requests
import pandas as pd
from pandas.io.json import json_normalize
from pandasql import sqldf

# Def

In [2]:
def api(param):
    
    url = 'https://api-football-v1.p.rapidapi.com/v3/' + param

    headers = {
        "X-RapidAPI-Key": "e613e8d615msha96b42823ece3a1p12cd95jsn12a8f361c699",
        "X-RapidAPI-Host": "api-football-v1.p.rapidapi.com"
    }

    response = requests.request("GET", url, headers=headers)
    
    return response.json()

# Load data

## Season

In [26]:
# api('seasons)

season_id = 2021

## Leagues

Run api

In [34]:
jLeagues = api('leagues')

Transform into dataframe

In [35]:
# Normalize from json
dfLeagues = pd.json_normalize(jLeagues['response'])

# Rename columns
dfLeagues.columns = dfLeagues.columns.str.replace('.', '_')

# Save into file
dfLeagues.drop('seasons', axis=1).to_csv('leagues.csv',index=False)

# Get league id
league_id = dfLeagues[(dfLeagues['country_name'] == 'England')\
                      & (dfLeagues['league_name'] == 'Premier League')]['league_id'].values[0]

/var/folders/hn/r6dxb61155x4z2mwg4dbmqtc0000gq/T/ipykernel_23302/1636317860.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  dfLeagues.columns = dfLeagues.columns.str.replace('.', '_')

## Teams

Run api

In [32]:
jTeams = api(f'teams?league={league_id}&season={season_id}')

Transform into dataframe

In [37]:
# Normalize from json
dfTeams = pd.json_normalize(jTeams['response'])

# Rename columns
dfTeams.columns = dfTeams.columns.str.replace('.', '_')

# Save into file
dfTeams.to_csv('teams.csv',index=False)

/var/folders/hn/r6dxb61155x4z2mwg4dbmqtc0000gq/T/ipykernel_23302/4269382596.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  dfTeams.columns = dfTeams.columns.str.replace('.', '_')

In [31]:
dfTeams

,team_id,team_name,team_code,team_country,team_founded,team_national,team_logo,venue_id,venue_name,venue_address,venue_city,venue_capacity,venue_surface,venue_image
0,33,Manchester United,MUN,England,1878,False,https://media-3.api-sports.io/football/teams/3...,556,Old Trafford,Sir Matt Busby Way,Manchester,76212,grass,https://media-3.api-sports.io/football/venues/...
1,34,Newcastle,NEW,England,1892,False,https://media-1.api-sports.io/football/teams/3...,562,St. James' Park,St. James&apos; Street,Newcastle upon Tyne,52389,grass,https://media-2.api-sports.io/football/venues/...
2,38,Watford,WAT,England,1881,False,https://media-1.api-sports.io/football/teams/3...,596,Vicarage Road,Vicarage Road,Watford,22200,grass,https://media-3.api-sports.io/football/venues/...
3,39,Wolves,WOL,England,1877,False,https://media-2.api-sports.io/football/teams/3...,600,Molineux Stadium,Waterloo Road,"Wolverhampton, West Midlands",32050,grass,https://media-1.api-sports.io/football/venues/...
4,40,Liverpool,LIV,England,1892,False,https://media-2.api-sports.io/football/teams/4...,550,Anfield,Anfield Road,Liverpool,55212,grass,https://media-1.api-sports.io/football/venues/...
5,41,Southampton,SOU,England,1885,False,https://media-3.api-sports.io/football/teams/4...,585,St. Mary's Stadium,Britannia Road,"Southampton, Hampshire",32689,grass,https://media-2.api-sports.io/football/venues/...
6,42,Arsenal,ARS,England,1886,False,https://media-1.api-sports.io/football/teams/4...,494,Emirates Stadium,Queensland Road,London,60383,grass,https://media-3.api-sports.io/football/venues/...
7,44,Burnley,BUR,England,1882,False,https://media-1.api-sports.io/football/teams/4...,512,Turf Moor,Harry Potts Way,Burnley,22546,grass,https://media-2.api-sports.io/football/venues/...
8,45,Everton,EVE,England,1878,False,https://media-1.api-sports.io/football/teams/4...,8560,Goodison Park,Goodison Road,Liverpool,40569,grass,https://media-3.api-sports.io/football/venues/...
9,46,Leicester,LEI,England,1884,False,https://media-3.api-sports.io/football/teams/4...,547,King Power Stadium,Filbert Way,"Leicester, Leicestershire",34310,grass,https://media-1.api-sports.io/football/venues/...
10,47,Tottenham,TOT,England,1882,False,https://media-3.api-sports.io/football/teams/4...,593,Tottenham Hotspur Stadium,"Bill Nicholson Way, 748 High Road",London,62850,grass,https://media-2.api-sports.io/football/venues/...
11,48,West Ham,WES,England,1895,False,https://media-3.api-sports.io/football/teams/4...,598,London Stadium,"Marshgate Lane, Stratford",London,62500,grass,https://media-2.api-sports.io/football/venues/...
12,49,Chelsea,CHE,England,1905,False,https://media-3.api-sports.io/football/teams/4...,519,Stamford Bridge,Fulham Road,London,41841,grass,https://media-3.api-sports.io/football/venues/...
13,50,Manchester City,MAC,England,1880,False,https://media-1.api-sports.io/football/teams/5...,555,Etihad Stadium,Rowsley Street,Manchester,55097,grass,https://media-1.api-sports.io/football/venues/...
14,51,Brighton,BRI,England,1901,False,https://media-2.api-sports.io/football/teams/5...,508,The American Express Community Stadium,Village Way,"Falmer, East Sussex",31800,grass,https://media-1.api-sports.io/football/venues/...
15,52,Crystal Palace,CRY,England,1905,False,https://media-3.api-sports.io/football/teams/5...,525,Selhurst Park,Holmesdale Road,London,26309,grass,https://media-1.api-sports.io/football/venues/...
16,55,Brentford,BRE,England,1889,False,https://media-3.api-sports.io/football/teams/5...,10503,Gtech Community Stadium,"166 Lionel Rd N, Brentford","Brentford, Middlesex",17250,grass,https://media-1.api-sports.io/football/venues/...
17,63,Leeds,LEE,England,1919,False,https://media-2.api-sports.io/football/teams/6...,546,Elland Road,Elland Road,"Leeds, West Yorkshire",40204,grass,https://media-3.api-sports.io/football/venues/...
18,66,Aston Villa,AST,England,1874,False,https://media-3.api-sports.io/football/teams/6...,495,Villa Park,Trinity Road,Birmingham,42788,grass,https://media-3.api-sports.io/football/venues/...
19,71,Norwich,NOR,England,1902,False,https://media-2.api-sports.io/football/teams/7...,565,Carrow Road,Carrow Road,"Norwich, Norfolk",27606,grass,https://media-2.api-sports.io/football/venues/...

## Game statistics

In [11]:
jGameStat = api('fixtures?live=all')

In [12]:
pd.json_normalize(jGameStat['response'])

,events,fixture.id,fixture.referee,fixture.timezone,fixture.date,fixture.timestamp,fixture.periods.first,fixture.periods.second,fixture.venue.id,fixture.venue.name,...,goals.home,goals.away,score.halftime.home,score.halftime.away,score.fulltime.home,score.fulltime.away,score.extratime.home,score.extratime.away,score.penalty.home,score.penalty.away
0,[],968407,None,UTC,2023-04-03T22:00:00+00:00,1680559200,1680559200,NaN,2245.0,Catherine Hall Sports Complex,...,0,0,0,0,None,None,None,None,None,None
1,"[{'time': {'elapsed': 17, 'extra': None}, 'tea...",980403,None,UTC,2023-04-03T21:30:00+00:00,1680557400,1680557400,NaN,1213.0,Estadio Antonio Aranda,...,1,1,1,1,None,None,None,None,None,None
2,[],1003376,"Bruno Sacarelo Roig,",UTC,2023-04-03T22:00:00+00:00,1680559200,1680559200,NaN,1641.0,Parque Cincuentenario Juan Gaspar Prandi,...,0,0,0,0,None,None,None,None,None,None
3,[],1014785,None,UTC,2023-04-03T22:00:00+00:00,1680559200,1680559200,NaN,1106.0,Grand Stade de Tanger,...,0,0,0,0,None,None,None,None,None,None
4,[],1014788,None,UTC,2023-04-03T22:00:00+00:00,1680559200,1680559200,NaN,1102.0,Stade Ben Ahmed El Abdi,...,0,0,0,0,None,None,None,None,None,None
5,[],1014790,None,UTC,2023-04-03T22:00:00+00:00,1680559200,1680559200,NaN,1109.0,Stade d'Honneur d'Oujda,...,0,0,0,0,None,None,None,None,None,None
6,"[{'time': {'elapsed': 33, 'extra': None}, 'tea...",1020423,None,UTC,2023-04-03T21:30:00+00:00,1680557400,1680557400,NaN,466.0,Estadio Monumental Banco Pichincha,...,1,0,1,0,None,None,None,None,None,None
7,"[{'time': {'elapsed': 7, 'extra': None}, 'team...",989602,R. Manjarrés,UTC,2023-04-03T21:00:00+00:00,1680555600,1680555600,1.680559e+09,373.0,Estadio General Santander,...,0,0,0,0,None,None,None,None,None,None
8,[],1012282,None,UTC,2023-04-03T21:00:00+00:00,1680555600,1680555600,1.680559e+09,NaN,Stade Taïeb Mhiri,...,0,0,0,0,None,None,None,None,None,None

## Squads

In [38]:
jSquad = api('players/squads?team=42')

In [20]:
pd.json_normalize(jSquad['response'])

,players,team.id,team.name,team.logo
0,"[{'id': 20355, 'name': 'A. Ramsdale', 'age': 2...",42,Arsenal,https://media-1.api-sports.io/football/teams/4...

## Players

In [23]:
jPlayer = api('players?id=20355&season=2022')

In [26]:
pd.json_normalize(jPlayer['response'])['statistics'][0]

[{'team': {'id': 42,
   'name': 'Arsenal',
   'logo': 'https://media-2.api-sports.io/football/teams/42.png'},
  'league': {'id': 39,
   'name': 'Premier League',
   'country': 'England',
   'logo': 'https://media-2.api-sports.io/football/leagues/39.png',
   'flag': 'https://media-2.api-sports.io/flags/gb.svg',
   'season': 2022},
  'games': {'appearences': 29,
   'lineups': 29,
   'minutes': 2610,
   'number': None,
   'position': 'Goalkeeper',
   'rating': '6.886206',
   'captain': False},
  'substitutes': {'in': 0, 'out': 0, 'bench': 0},
  'shots': {'total': None, 'on': None},
  'goals': {'total': 0, 'conceded': 27, 'assists': None, 'saves': 70},
  'passes': {'total': 674, 'key': None, 'accuracy': 14},
  'tackles': {'total': 1, 'blocks': None, 'interceptions': None},
  'duels': {'total': 9, 'won': 9},
  'dribbles': {'attempts': 1, 'success': 1, 'past': None},
  'fouls': {'drawn': 3, 'committed': None},
  'cards': {'yellow': 0, 'yellowred': 0, 'red': 0},
  'penalty': {'won': None,
   'commited': None,
   'scored': 0,
   'missed': 0,
   'saved': 0}},
 {'team': {'id': 42,
   'name': 'Arsenal',
   'logo': 'https://media-2.api-sports.io/football/teams/42.png'},
  'league': {'id': 3,
   'name': 'UEFA Europa League',
   'country': 'World',
   'logo': 'https://media-1.api-sports.io/football/leagues/3.png',
   'flag': None,
   'season': 2022},
  'games': {'appearences': 3,
   'lineups': 3,
   'minutes': 300,
   'number': None,
   'position': 'Goalkeeper',
   'rating': '6.666666',
   'captain': False},
  'substitutes': {'in': 0, 'out': 0, 'bench': 5},
  'shots': {'total': None, 'on': None},
  'goals': {'total': 0, 'conceded': 3, 'assists': None, 'saves': 6},
  'passes': {'total': 92, 'key': None, 'accuracy': 17},
  'tackles': {'total': None, 'blocks': None, 'interceptions': None},
  'duels': {'total': 1, 'won': None},
  'dribbles': {'attempts': None, 'success': None, 'past': None},
  'fouls': {'drawn': None, 'committed': None},
  'cards': {'yellow': 0, 'yellowred': 0, 'red': 0},
  'penalty': {'won': None,
   'commited': None,
   'scored': 0,
   'missed': 0,
   'saved': 0}},
 {'team': {'id': 10,
   'name': 'England',
   'logo': 'https://media-2.api-sports.io/football/teams/10.png'},
  'league': {'id': 5,
   'name': 'UEFA Nations League',
   'country': 'World',
   'logo': 'https://media-1.api-sports.io/football/leagues/5.png',
   'flag': None,
   'season': 2022},
  'games': {'appearences': 2,
   'lineups': 2,
   'minutes': 180,
   'number': None,
   'position': 'Goalkeeper',
   'rating': '5.300000',
   'captain': False},
  'substitutes': {'in': 0, 'out': 0, 'bench': 4},
  'shots': {'total': None, 'on': None},
  'goals': {'total': 0, 'conceded': 4, 'assists': None, 'saves': 1},
  'passes': {'total': 16, 'key': None, 'accuracy': 15},
  'tackles': {'total': None, 'blocks': None, 'interceptions': None},
  'duels': {'total': None, 'won': None},
  'dribbles': {'attempts': None, 'success': None, 'past': None},
  'fouls': {'drawn': None, 'committed': None},
  'cards': {'yellow': 0, 'yellowred': 0, 'red': 0},
  'penalty': {'won': None,
   'commited': None,
   'scored': 0,
   'missed': 0,
   'saved': 0}},
 {'team': {'id': 10,
   'name': 'England',
   'logo': 'https://media-1.api-sports.io/football/teams/10.png'},
  'league': {'id': 1,
   'name': 'World Cup',
   'country': 'World',
   'logo': 'https://media-1.api-sports.io/football/leagues/1.png',
   'flag': None,
   'season': 2022},
  'games': {'appearences': 0,
   'lineups': 0,
   'minutes': 0,
   'number': None,
   'position': 'Goalkeeper',
   'rating': None,
   'captain': False},
  'substitutes': {'in': 0, 'out': 0, 'bench': 5},
  'shots': {'total': None, 'on': None},
  'goals': {'total': 0, 'conceded': 0, 'assists': None, 'saves': None},
  'passes': {'total': None, 'key': None, 'accuracy': None},
  'tackles': {'total': None, 'blocks': None, 'interceptions': None},
  'duels': {'total': None, 'won': None},
  'dribbles': {'attempts': None, 'success': None, 'past': None},
  'fouls': {'drawn': None, 'committed': None},
  'cards': {'yellow': 0, 'yellowred': 0, 'red': 0},
  'penalty': {'won': None,
   'commited': None,
   'scored': 0,
   'missed': 0,
   'saved': 0}}]

## Players statistics

In [ ]:
jPlayerStat = api('fixtures/players')

In [ ]:
pd.json_normalize(jPlayerStat['response'])

## Transfers

In [27]:
jTransfer = api('transfers?player=20355')

In [29]:
pd.json_normalize(jTransfer['response'])

,update,transfers,player.id,player.name
0,2023-04-03T06:24:08+00:00,"[{'date': '2021-08-20', 'type': '€ 28M', 'team...",20355,A. Ramsdale